// <auto-generated />
namespace HabeebFootwear.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Vednor_Name_set_Required : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Vednor_Name_set_Required));
        
        string IMigrationMetadata.Id
        {
            get { return "201909051224224_Vednor_Name_set_Required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
