// <auto-generated />
namespace HabeebFootwear.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Vendor_DeleteStatus_Field_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Vendor_DeleteStatus_Field_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201909051044406_Vendor_DeleteStatus_Field_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
